<?php
/**
 * AspectConstraintTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Taxonomy API
 *
 * Use the Taxonomy API to discover the most appropriate eBay categories under which sellers can offer inventory items for sale, and the most likely categories under which buyers can browse or search for items to purchase. In addition, the Taxonomy API provides metadata about the required and recommended category aspects to include in listings, and also has two operations to retrieve parts compatibility information.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * AspectConstraintTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains information about the formatting, occurrence, and support of an aspect.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AspectConstraintTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AspectConstraint"
     */
    public function testAspectConstraint()
    {
    }

    /**
     * Test attribute "aspect_applicable_to"
     */
    public function testPropertyAspectApplicableTo()
    {
    }

    /**
     * Test attribute "aspect_data_type"
     */
    public function testPropertyAspectDataType()
    {
    }

    /**
     * Test attribute "aspect_enabled_for_variations"
     */
    public function testPropertyAspectEnabledForVariations()
    {
    }

    /**
     * Test attribute "aspect_format"
     */
    public function testPropertyAspectFormat()
    {
    }

    /**
     * Test attribute "aspect_max_length"
     */
    public function testPropertyAspectMaxLength()
    {
    }

    /**
     * Test attribute "aspect_mode"
     */
    public function testPropertyAspectMode()
    {
    }

    /**
     * Test attribute "aspect_required"
     */
    public function testPropertyAspectRequired()
    {
    }

    /**
     * Test attribute "aspect_usage"
     */
    public function testPropertyAspectUsage()
    {
    }

    /**
     * Test attribute "expected_required_by_date"
     */
    public function testPropertyExpectedRequiredByDate()
    {
    }

    /**
     * Test attribute "item_to_aspect_cardinality"
     */
    public function testPropertyItemToAspectCardinality()
    {
    }
}
